version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - npm run build
artifacts:
  files:
    - static/*
    - asset-manifest.json
    - index.html
    - manifest.json
    - service-worker.js
