version: 0.2

phases:
  install:
    runtime-versions:
      node: 10
    commands:
      - echo Installing dependencies
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - npm run build
  post_build:
    commands:
      - aws s3 sync build/ s3://markmorrison-personal
